# Generated by Django 2.1.5 on 2019-01-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('release_date', models.TextField()),
                ('trailer_url', models.TextField()),
                ('image_path', models.TextField()),
                ('backdrop_path', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('vote_count', models.IntegerField()),
                ('vote_average', models.FloatField()),
            ],
        ),
    ]
