# Generated by Django 2.1.5 on 2019-01-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='reserve_path',
            field=models.TextField(default=None),
        ),
    ]
